name = "MyPkgTemplates"
uuid = "df9f8480-9bd5-44b7-831b-75f25844f7e4"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
